abstract: L<Catalyst::Plugin::Upload::Digest> example application
author: E<AElig>var ArnfjE<ouml>rE<eth> Bjarmason <avar@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Upload-Digest
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7006
  Catalyst::Plugin::Upload::Digest: 0.01
  Catalyst::View::TT: 0.24
version: 0.01
